//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StravaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string ActivityType { get; set; }
        public string GearId { get; set; }
        public Nullable<decimal> AverageCadence { get; set; }
        public Nullable<decimal> AverageHeartRate { get; set; }
        public Nullable<System.DateTime> TimeStarted { get; set; }
        public Nullable<System.DateTime> TimeEnded { get; set; }
        public Nullable<decimal> ElevationGain { get; set; }
    }
}
